mode              : LIVE
data_csv          : data/BTC_1hour.csv
coins             : ALL_USDT
max_concurrent    : 5
risk_pct          : 16.0        # işlemlerde sermayenin %1’i
debug             : TRUE
base_usdt_per_trade: 10

default_params:
  leverage          : 4
  sl_pct            : 3.0
  tp_pct            : 6.0
  history_limit     : 50           # geçmiş mumlar
  commission_pct : 0.04            # back-testte kullan
  slippage_pct   : 0.01
  expire_sec     : 720

strategies:
  - name: super_trend
    timeframes: ["1m", "15m"]
    params:
      atr_period: 12
      multiplier: 3.0
    overrides:
      leverage : 5
      sl_pct   : 2.0
      tp_pct   : 4.0


